export const EMOJI_OPTIONS = [
  { emoji: "🦞", kw: "lobster claw" },
  { emoji: "🐙", kw: "octopus" },
  { emoji: "🦊", kw: "fox" },
  { emoji: "🐺", kw: "wolf" },
  { emoji: "🦁", kw: "lion" },
  { emoji: "🐯", kw: "tiger" },
  { emoji: "🐻", kw: "bear" },
  { emoji: "🦄", kw: "unicorn" },
  { emoji: "🐬", kw: "dolphin" },
  { emoji: "🦈", kw: "shark" },
  { emoji: "🐉", kw: "dragon" },
  { emoji: "🦅", kw: "eagle" },
  { emoji: "🦉", kw: "owl" },
  { emoji: "🐝", kw: "bee" },
  { emoji: "🦋", kw: "butterfly" },
  { emoji: "🔥", kw: "fire hot" },
  { emoji: "⚡", kw: "lightning bolt electric" },
  { emoji: "💎", kw: "diamond gem" },
  { emoji: "🚀", kw: "rocket launch" },
  { emoji: "🛡️", kw: "shield protect" },
  { emoji: "⚔️", kw: "sword fight" },
  { emoji: "🔮", kw: "crystal ball magic" },
  { emoji: "💡", kw: "light idea" },
  { emoji: "🎯", kw: "target aim" },
  { emoji: "🎨", kw: "art paint" },
  { emoji: "📡", kw: "satellite antenna" },
  { emoji: "🔬", kw: "microscope science" },
  { emoji: "🧲", kw: "magnet" },
  { emoji: "🗝️", kw: "key" },
  { emoji: "📦", kw: "package box" },
  { emoji: "🧰", kw: "toolbox" },
  { emoji: "🎲", kw: "dice game" },
  { emoji: "⭐", kw: "star" },
  { emoji: "🌙", kw: "moon night" },
  { emoji: "☀️", kw: "sun" },
  { emoji: "🌊", kw: "wave ocean" },
  { emoji: "🌿", kw: "leaf plant" },
  { emoji: "🍀", kw: "clover luck" },
  { emoji: "❄️", kw: "snow ice" },
  { emoji: "🏗️", kw: "building construction" },
  { emoji: "🤖", kw: "robot bot ai" },
  { emoji: "👾", kw: "alien game" },
  { emoji: "🎮", kw: "game controller" },
  { emoji: "🔧", kw: "wrench tool" },
  { emoji: "⚙️", kw: "gear settings" },
  { emoji: "🏠", kw: "house home" },
  { emoji: "🏢", kw: "office building" },
  { emoji: "🌐", kw: "globe world web" },
  { emoji: "📊", kw: "chart data" },
  { emoji: "🔒", kw: "lock security" },
];

export const FEATURED_COUNT = 20;
